"""Add skill_id to StudentSkill table for table-based matching

Revision ID: 3997af5de1b6
Revises: 9df9055d16d5
Create Date: 2026-03-28 17:09:48.618262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3997af5de1b6'
down_revision = '9df9055d16d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('skill_id')

    # ### end Alembic commands ###
