"""sync

Revision ID: 7fab809f905b
Revises: 3997af5de1b6
Create Date: 2026-03-29 16:48:50.474837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fab809f905b'
down_revision = '3997af5de1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('email_weekly_report', sa.Boolean(), nullable=True),
    sa.Column('email_new_assignments', sa.Boolean(), nullable=True),
    sa.Column('compact_sidebar', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_alert', schema=None) as batch_op:
        batch_op.create_index('ix_student_alert_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_student_alert_student_resolved', ['student_id', 'is_resolved'], unique=False)

    with op.batch_alter_table('student_note', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False))

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_code', sa.String(length=16), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_profile_student_code'), ['student_code'], unique=True)
        batch_op.drop_column('university')
        batch_op.drop_column('linkedin_profile')
        batch_op.drop_column('bio')
        batch_op.drop_column('current_year')
        batch_op.drop_column('career_goal')
        batch_op.drop_column('github_profile')
        batch_op.drop_column('profile_picture')

    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_id', sa.Integer(), nullable=True))
        batch_op.create_index('ix_student_skill_student_id', ['student_id'], unique=False)
        batch_op.create_foreign_key(None, 'skills', ['skill_id'], ['id'])

    with op.batch_alter_table('teacher_assignment', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_assignment_student_id', ['student_id'], unique=False)
        batch_op.create_index('ix_teacher_assignment_teacher_id', ['teacher_id'], unique=False)
        batch_op.create_unique_constraint('uq_teacher_student_assignment', ['teacher_id', 'student_id'])

    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('personal_webpage', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('cell_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('cell_phone')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('personal_webpage')
        batch_op.drop_column('faculty')
        batch_op.drop_column('designation')

    with op.batch_alter_table('teacher_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_teacher_student_assignment', type_='unique')
        batch_op.drop_index('ix_teacher_assignment_teacher_id')
        batch_op.drop_index('ix_teacher_assignment_student_id')

    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_student_skill_student_id')
        batch_op.drop_column('skill_id')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('github_profile', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('career_goal', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_year', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bio', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('linkedin_profile', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('university', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_student_profile_student_code'))
        batch_op.drop_column('student_code')

    with op.batch_alter_table('student_note', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    with op.batch_alter_table('student_alert', schema=None) as batch_op:
        batch_op.drop_index('ix_student_alert_student_resolved')
        batch_op.drop_index('ix_student_alert_created_at')

    op.drop_table('student_settings')
    # ### end Alembic commands ###
