"""Sync after stamp

Revision ID: 8842718bc37e
Revises: 0e1b8dbe027b
Create Date: 2026-02-14 19:52:09.074993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8842718bc37e'
down_revision = '0e1b8dbe027b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_skill', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('study_sessions_related_skill_id_fkey'), type_='foreignkey')
        batch_op.drop_column('related_skill_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_skill_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('study_sessions_related_skill_id_fkey'), 'skills', ['related_skill_id'], ['id'])
        batch_op.drop_column('related_skill')

    # ### end Alembic commands ###
