"""add extended profile fields to teacher_profile

Revision ID: 9df9055d16d5
Revises: de3d225fdbe9
Create Date: 2026-03-23 23:31:14.964514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df9055d16d5'
down_revision = 'de3d225fdbe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('designation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('personal_webpage', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('cell_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_profile', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('cell_phone')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('personal_webpage')
        batch_op.drop_column('faculty')
        batch_op.drop_column('designation')

    # ### end Alembic commands ###
