"""Add missing profile tracking fields

Revision ID: d1ad604d254c
Revises: 7fab809f905b
Create Date: 2026-03-29 20:30:28.119216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ad604d254c'
down_revision = '7fab809f905b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('current_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('career_goal', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('linkedin_profile', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('github_profile', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('profile_picture', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('profile_picture')
        batch_op.drop_column('bio')
        batch_op.drop_column('github_profile')
        batch_op.drop_column('linkedin_profile')
        batch_op.drop_column('career_goal')
        batch_op.drop_column('current_year')
        batch_op.drop_column('university')

    # ### end Alembic commands ###
