"""remove profile_visibility from student_settings

Revision ID: de3d225fdbe9
Revises: d5e6f7a8b9c0
Create Date: 2026-03-23 23:15:06.618668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3d225fdbe9'
down_revision = 'd5e6f7a8b9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_settings', schema=None) as batch_op:
        batch_op.drop_column('profile_visibility')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_visibility', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
