"""add indexes and uniqueconstraint to teacher tables

Revision ID: e38e38a9c801
Revises: add_target_cgpa_001
Create Date: 2026-02-25 17:45:17.448449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38e38a9c801'
down_revision = 'add_target_cgpa_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_alert', schema=None) as batch_op:
        batch_op.create_index('ix_student_alert_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_student_alert_student_resolved', ['student_id', 'is_resolved'], unique=False)

    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.create_index('ix_student_skill_student_id', ['student_id'], unique=False)

    with op.batch_alter_table('teacher_assignment', schema=None) as batch_op:
        batch_op.create_index('ix_teacher_assignment_student_id', ['student_id'], unique=False)
        batch_op.create_index('ix_teacher_assignment_teacher_id', ['teacher_id'], unique=False)
        batch_op.create_unique_constraint('uq_teacher_student_assignment', ['teacher_id', 'student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_assignment', schema=None) as batch_op:
        batch_op.drop_constraint('uq_teacher_student_assignment', type_='unique')
        batch_op.drop_index('ix_teacher_assignment_teacher_id')
        batch_op.drop_index('ix_teacher_assignment_student_id')

    with op.batch_alter_table('student_skill', schema=None) as batch_op:
        batch_op.drop_index('ix_student_skill_student_id')

    with op.batch_alter_table('student_alert', schema=None) as batch_op:
        batch_op.drop_index('ix_student_alert_student_resolved')
        batch_op.drop_index('ix_student_alert_created_at')

    # ### end Alembic commands ###
