"""update study session model

Revision ID: 0e1b8dbe027b
Revises: 4c1949603621
Create Date: 2026-02-14 14:43:00.654285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e1b8dbe027b'
down_revision = '4c1949603621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_skill', sa.String(length=255), nullable=True))
        batch_op.drop_column('related_skills')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('related_skills', sa.String(), autoincrement=False, nullable=True))
        batch_op.drop_column('related_skill')

    # ### end Alembic commands ###
